sonar.projectKey=nnpvaan_evat-smartcharge-ai-backend
sonar.organization=nnpvaan

sonar.projectName=EVAT SmartCharge AI Backend API
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests

sonar.python.coverage.reportPaths=reports/coverage.xml

sonar.exclusions=venv/**,security-venv/**,__pycache__/**,reports/**
sonar.coverage.exclusions=tests/**

sonar.sourceEncoding=UTF-8